### ISSUE TITLE
Chapters 1 and 2: Undefined functions in Source Academy

### ISSUE THREAD

**Issue by JoyPP** [source-academy/sicp#1]
There are some functions in the textbook undefined in Source Academy platform:
Chapter1:
1) In 1.1.8, function `math_log`, `math_exp` undefined;
2) In 1.2.6, a) function `math_random`, `math_floor` undefined;
	          b) Library Math undefined;
3) In 1.3.3, function `math_sin`, `math_cos` undefined;

Chapter2:
1) In 2.2.4, function `make_painter_from_url` undefined;
2) In 2.3.3, a) In first `is_element_set` program, function `is_equal` undefined;
                   b) In Exercise 2.62, function `quotient` undefined;
                   c) In `look_up` program, function `is_equal` and `key` undefined
3) In 2.3.4, function `symbol_leaf` undefined；
4) In 2.4.3, function `get` undefined;
5) In 2.5.2, function `put`, `put_coercion`, `get_coercion` undefined;

**Comment by martin-henz** [comment]
All done except the last one
