### ISSUE TITLE
Chapter 2.4.3: math_atan2 should be used for two-argument arctangent

### ISSUE THREAD

**Issue by PossibilityZero** [source-academy/sicp#1006]
Code snippets in Chapter 2.4.3 call the `math_atan` function with two arguments `(y, x)`, which causes errors if the selectors in question are used. This should be changed to use [`math_atan2`](https://docs.sourceacademy.org/source_2/global.html#math_atan2) as specified in the Source docs.

**Comment by martin-henz** [comment]
I found various other references to math_atan, instead of math_atan2:
```
	modified:   xml/chapter2/section4/subsection2.xml
	modified:   xml/chapter2/section4/subsection3.xml
	modified:   xml/chapter2/section5/subsection2.xml
```
