### ISSUE TITLE
SVG: cons car cdr in figure 2.1

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#134]
(this may be handled already in a pending PR, so I'm including it here in case it isn't)

<img width="629" alt="Screenshot 2019-08-05 at 11 35 01 AM" src="https://user-images.githubusercontent.com/30220768/62437281-23ba9d80-b775-11e9-8427-093b20dd0ed1.png">

**Comment by TobiasWrigstad** [comment]
Looking Into it.

**Comment by TobiasWrigstad** [comment]
It seems this one is fixed in a clean build?

**Comment by martin-henz** [comment]
Yes, closing it. Tx.
