### ISSUE TITLE
WEB: book title on title page could be a bit lighter

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#140]
I like the change to grey. White was too stark and boring. However, I feel it's a bit less prominent than it should be, and less readable.

<img width="696" alt="Screenshot 2019-08-07 at 9 38 17 AM" src="https://user-images.githubusercontent.com/30220768/62588215-850a7a00-b8f7-11e9-9b62-264990bf82b1.png">

I'd suggest a slightly lighter grey.

**Comment by TobiasWrigstad** [comment]
What about this:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/364888/62628472-fb41c780-b95d-11e9-8012-07389df76d38.png">
(below is white for reference)
<img width="377" alt="image" src="https://user-images.githubusercontent.com/364888/62628530-0f85c480-b95e-11e9-8bba-2bdf4eac48bd.png">

**Comment by martin-henz** [comment]
Kelly likes the first one! Just a bit off-white.

-martin
http://www.comp.nus.edu.sg/~henz

**Comment by TobiasWrigstad** [comment]
Sold! :)
