### ISSUE TITLE
Solutions to Exercise 4.1

### ISSUE THREAD

**Issue by travisryte** [source-academy/sicp#158]
https://sicp.comp.nus.edu.sg/chapters/75#ex_4.1

Solution to write a version of list_of_values that evaluates operands from right to left., 
Apply reverse on operands(stmt) for is_application(stmt) in evaluate(stmt, env)
```
Initially: 
is_application(stmt)
          ? apply(evaluate(operator(stmt), env),
                  list_of_values(operands(stmt), env))
Changed:
is_application(stmt)
          ? apply(evaluate(operator(stmt), env),
                  list_of_values(reverse(operands(stmt)), env))
```
A few test cases:
```
parse_and_eval("1 / 3;"); //returns 3 instead of 0.3333
parse_and_eval("1 - 3 * 4;"); //returns 11 instead of -11
```

**Comment by martin-henz** [comment]
You misunderstood the exercise. It is not asking you to reverse the order of arguments, but to evaluate the arguments from left to right (or from right to left).

With left-to-right evaluation, you get this:
``display(4) - display(1); // evaluates to 3, and displays first 4 and then 1``

With right-to-left evaluation, you get this:
``display(4) - display(1); // evaluates to 3, and displays first 1 and then 4``
