### ISSUE TITLE
Solution to exercise 1.13

### ISSUE THREAD

**Issue by GorillaGambit** [source-academy/sicp#159]
Here is the solution in LaTex, along with an image of its evaluation

![image](https://user-images.githubusercontent.com/50513077/69049204-4c238a80-0a3a-11ea-8e7a-9b94350a17aa.png)

\documentclass[12pt, letterpaper]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{multicol}
\usepackage[margin=0.8in]{geometry}

\begin{document}

\large
First, we show that $\textrm{Fib}(n) = \dfrac{\phi^n-\psi^n}{\sqrt{5}}$, where $\psi = \dfrac{1-\sqrt{5}}{2}$ using strong induction.
\\
$\textrm{Fib}(0) = 0$ and $ \dfrac{\phi^0-\psi^0}{\sqrt{5}} = 0$
\\
$\textrm{Fib}(1) = 1$ and $\dfrac{\phi^1-\psi^1}{\sqrt{5}} = \dfrac{\dfrac{1}{2}\left(1+\sqrt{5} - 1 + \sqrt{5}\right)}{\sqrt{5}} = 1$
\\
So the statement is true for $n=0,1$. Given $m \geq 2$, assume the proposition to be true for $0, 1, \dots , m$.
\\
$\textrm{Fib}(m+1) = \textrm{Fib}(m) + \textrm{Fib}(m-1) = \dfrac{\phi^m-\psi^m + \phi^{m-1} - \psi^{m-1}}{\sqrt{5}}
\\
= \dfrac{\phi^{m-1}(\phi + 1) - \psi^{m-1}(\psi + 1)}{\sqrt{5}}
\\
=\dfrac{\phi^{m-1}(\phi^2) - \psi^{m-1}(\psi^2)}{\sqrt{5}} = \dfrac{\phi^{m+1} - \psi^{m+1}}{\sqrt{5}}$, so the statement is true.
\\\\
Notice that since $|\psi| < 1$ and $\sqrt{5} > 2$, one has $\left|\dfrac{\psi^n}{\sqrt{5}}\right| < \dfrac{1}{2}$
\\
Then the integer closest to $\textrm{Fib}(n) + \dfrac{\psi^n}{\sqrt{5}} = \dfrac{\phi^n}{\sqrt{5}}$ is $\textrm{Fib}(n)$.

\end{document}

**Comment by martin-henz** [comment]
As it is written, your strong induction has a flaw: You assume the statement to hold for m >= 2, and prove that it holds for m + 1. But you never prove that the statement holds for n = 2. Luckily, in your prove, you don't make use of the condition m >= 2, so you can change it to m >= 1. This would close the gap.

**Comment by GorillaGambit** [comment]
I have made the changes below.
![image](https://user-images.githubusercontent.com/50513077/69126282-d32c3d80-0ae2-11ea-922a-2b3a7aed27cd.png)

\documentclass[12pt, letterpaper]{article}
\usepackage[utf8]{inputenc}%codification of the document
\usepackage{amsmath}
\usepackage{multicol}
\usepackage[margin=0.8in]{geometry}

%Here begins the body of the document
\begin{document}


\large
First, we show that $\textrm{Fib}(n) = \dfrac{\phi^n-\psi^n}{\sqrt{5}}$, where $\psi = \dfrac{1-\sqrt{5}}{2}$ using strong induction.
\\
$\textrm{Fib}(0) = 0$ and $ \dfrac{\phi^0-\psi^0}{\sqrt{5}} = 0$
\\
$\textrm{Fib}(1) = 1$ and $\dfrac{\phi^1-\psi^1}{\sqrt{5}} = \dfrac{\dfrac{1}{2}\left(1+\sqrt{5} - 1 + \sqrt{5}\right)}{\sqrt{5}} = 1$
\\
So the statement is true for $n=0,1$. Given $n \geq 1$, assume the proposition to be true for $0, 1, \dots , n$.
\\
$\textrm{Fib}(n+1) = \textrm{Fib}(n) + \textrm{Fib}(n-1) = \dfrac{\phi^n-\psi^n + \phi^{n-1} - \psi^{n-1}}{\sqrt{5}}
\\
= \dfrac{\phi^{n-1}(\phi + 1) - \psi^{n-1}(\psi + 1)}{\sqrt{5}}
\\
=\dfrac{\phi^{n-1}(\phi^2) - \psi^{n-1}(\psi^2)}{\sqrt{5}} = \dfrac{\phi^{n+1} - \psi^{n+1}}{\sqrt{5}}$, so the statement is true.
\\\\
Notice that since $|\psi| < 1$ and $\sqrt{5} > 2$, one has $\left|\dfrac{\psi^n}{\sqrt{5}}\right| < \dfrac{1}{2}$
\\
Then the integer closest to $\textrm{Fib}(n) + \dfrac{\psi^n}{\sqrt{5}} = \dfrac{\phi^n}{\sqrt{5}}$ is $\textrm{Fib}(n)$.

\end{document}
