### ISSUE TITLE
WEB: Sidebar Navigation Font Color (using Edge browser)

### ISSUE THREAD

**Issue by sahil48** [source-academy/sicp#181]
![image](https://user-images.githubusercontent.com/6100774/70851186-24b8b580-1e60-11ea-884b-79b0cadda42c.png)

When I click on the hamburger button in Microsoft Edge on Windows 10, the font is the same color as the background, and invisible until I hover the mouse over a given title.

**Comment by martin-henz** [comment]
Wow, indeed need to pay attention to Edge from now on. Our "preferred" browsers are still Chrome and Firefox, but we should include Edge soon as "preferred".
