### ISSUE TITLE
Suggest using codeboot.org and link examples to run automatically with codeboot

### ISSUE THREAD

**Issue by feeley** [source-academy/sicp#183]
I was just told about the "SICP in JS" and am quite excited with it being available.

At the University of Montreal we have switched to using JS to teach introductory programming and have designed the codeboot.org "JavaScript runner" to allow students to start programming immediately without having to install any software.  Many JS runners exist, but codeboot has two unique features for teaching novices: a fine-grained single stepper, and launching the execution of a specific snippet of JS embedded in a URL (in web pages, class notes, etc), like this:

http://codeboot.org/query.cgi?replay=var%20f%20=%20function%20(x)%20{%20return%20x*x;%20};%20f(1+2*3);@S

It would be great if the links to the solutions in the PDF and web pages could include a link to codeboot to easily run the code.  I think this would add a lot of value for the intended audience.

**Comment by martin-henz** [comment]
The Source Academy has a single stepper, too, see here:
https://tinyurl.com/SICPJS-stepper

The Source Academy is custom-made for SICP JS. A key feature is proper tail calls, even for browsers who do not support ECMAScript 2015 in this respect, see:
https://tinyurl.com/SICPJS-PTC

See here for the full announcement:
https://sicp.comp.nus.edu.sg/announcement.html

As you can see, we are quite committed to the Source Academy :-)
