### ISSUE TITLE
WEB: References to footnotes not working

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#186]
Example: 1.2.6

<img width="912" alt="Screenshot 2020-01-05 at 4 58 08 PM" src="https://user-images.githubusercontent.com/30220768/71777568-b8ebe780-2fdc-11ea-99e7-9830a2b594d8.png">

**Comment by gerhean** [comment]
Seems like its already fixed?
![image](https://user-images.githubusercontent.com/16630400/81494242-e5d93f80-92d9-11ea-9049-f9750a032081.png)

**Comment by Persdre** [comment]
> Seems like its already fixed?
> ![image](https://user-images.githubusercontent.com/16630400/81494242-e5d93f80-92d9-11ea-9049-f9750a032081.png)
