### ISSUE TITLE
Look for tag <JAVASCRIPT_RUN>...

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#189]
...and see if it can be avoided. Many occurrences stem from the previous need to use a different name when predeclared functions are re-declared.

**Comment by gerhean** [comment]
Can be detected by adding a console.log to:
\sicp\javascript\processingFunctions\processSnippetJs.js 
line 77

**Comment by gerhean** [comment]
making a script to smoke out bad tags

**Comment by martin-henz** [comment]
> currently making a script to smoke out bad tags

That's great!
