### ISSUE TITLE
EPUB: missing elements

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#190]
A user reports:

Just a wanted to let you know, the epub version is a bit broken. Some italicized words and several other elements do not display at all, which is why I have to go back and forth from my kindle to my phone when I feel something is missing, to read that part. :(

Epub reader used:  Kindle 10

See: https://www.reddit.com/r/scheme/comments/ea1f8w/sicp_js_going_public/

**Comment by gerhean** [comment]
Might need to add some screenshots to illustrate the problem more clearly.
