### ISSUE TITLE
Figure 3.5 in Subsection 3.2.2 is wrong

### ISSUE THREAD

**Issue by KiriaKasis** [source-academy/sicp#192]
In the figure 5 frames are shown, as it is shown now given the code example

> function square(x) {
>     return x * x;
> }
> 
> function sum_of_squares(x, y) {
>     return square(x) + square(y);
> }
> 
> function f(a) {
>     return sum_of_squares(a + 1, a * 2);
> }
> 
> f(5);

Figure 3.5 shows that all 4 frames of function invocation (f (E1), sum_of_squares (E2), square (E3), square (E4)) point to the main program frame.

I believe that only E1 should point to the main program frame, E2 should point to E1, and both E3 and E4 should point to E2.

**Comment by KiriaKasis** [comment]
I forgot to include a direct link to the [figure 3.5](https://sicp.comp.nus.edu.sg/chapters/54#fig_3.5) in the issue

**Comment by martin-henz** [comment]
The current figure is correct. All frames point to the program environment, because the program environment is the environment of all the function values: f and sum_of_squares.
