### ISSUE TITLE
Simply treat function bodies as blocks

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#268]
I'm considering a rather drastic step, after having written https://source-academy.github.io/chapters/3.2.4.html#p2

I think this is an unnecessary complication. It would be cleaner to treat the body of functions simply as blocks. Then the issue in 3.2.4 shifts in the right direction: What is the semantics of a block? This way, we would not have to revise the core of the environment model in 3.2.4. This would also simplify 4.1 quite a bit and would eliminate the issue addressed by https://source-academy.github.io/chapters/4.1.7.html#ex_4.22

This would be a significant change, and I would tackle the writing first.

To illustrate the issue:

<img width="785" alt="Screenshot 2020-06-26 at 11 41 07 AM" src="https://user-images.githubusercontent.com/30220768/85817952-fec28500-b7a1-11ea-8b94-05efea11cb2a.png">

In this proposal, E1 would be split into two frames: one for x and one for the body block (good_enough etc).

Strictly speaking, this would be a deviation from JavaScript: JavaScript clearly distinguishes the body of functions from regular blocks. For example, it prevents a re-declaration of a parameter in the body. Such a re-declaration would be perfectly fine if the body of functions would be blocks. In this proposal, I'm suggesting to simply add a footnote that adds the restriction that function bodies may not redeclare parameters. Or we could just ignore the issue in the textbook and just include it in the Source specifications.

What do you think @TobiasWrigstad ?

**Comment by TobiasWrigstad** [comment]
I have mulled this over, and I want to sleep on it until tomorrow but a preliminary respons is that I am 100% for the idea. It seems to make things a lot simpler and the deviation from JavaScript is not too big. I think we need the footnote in the textbook to avoid getting too many "helpful suggestions" by email.

**Comment by martin-henz** [comment]
OK, standing by for now. I'll look at your chapter 1 comment and other issues first.

**Comment by TobiasWrigstad** [comment]
I've thought about it some more, and I am convinced it is the right move. A lot of unnecessary complexity for no real gain can be removed.

**Comment by martin-henz** [comment]
That's great. I'll go ahead, then.

BTW, I'm done with LP (4.4). Really really neat. My totally unbiased view
is that it's much better than the original.

More later.

-martin
http://www.comp.nus.edu.sg/~henz

**Comment by martin-henz** [comment]
I've made the necessary changes in the textbook, see https://github.com/source-academy/sicp/pull/280

If you haven't reached the relevant parts yet, we could merge this PR without review. 

Up to you to review the PR separately.
