### ISSUE TITLE
[CHAP 2 BUG] Chap 2.3.4 incorrect picture

### ISSUE THREAD

**Issue by benclmnt** [source-academy/sicp#275]
![image](https://user-images.githubusercontent.com/49342399/85952678-8fb18000-b99d-11ea-8ea5-a0a715040501.png)
I think there is a mistake in the picture, as it is not fixed-length encoding. This picture is also referenced in the later paragraph (and correctly so) that talks about variable-length encoding.

**Comment by TobiasWrigstad** [comment]
Indeed -- the figure sources are wrong. It should be
```
A 000   C 010   E 100   G 110
B 001   D 011   F 101   H 111
```
The root cause seems to be that `static/img_tex/ch2_3_4-1.png` and `static/img_tex/ch2_3_4-2.png` both have the content of `static/img_tex/ch2_3_4-2.png` and `static/img_tex/ch2_3_4-1.png` is simply wrong.
