### ISSUE TITLE
SVGPDF: Figure 5.11 has labels missing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#298]
Current (JS) version of figure 5.11:

<img width="511" alt="Screenshot 2020-07-07 at 12 27 34 PM" src="https://user-images.githubusercontent.com/30220768/86710417-87b4a880-c04d-11ea-8bc6-936ccd6ce7aa.png">

Original (Scheme):

<img width="659" alt="Screenshot 2020-07-07 at 12 28 14 PM" src="https://user-images.githubusercontent.com/30220768/86710444-8edbb680-c04d-11ea-8bd3-56dd90278d65.png">

**Comment by martin-henz** [comment]
Labels are confused; leaving the issue open

**Comment by TobiasWrigstad** [comment]
Hopefully managed to address both now. The problem with inkscape on the Mac is that XQuartz wont let me have both the right image and the editing one on the screen at the same time. And apparently I suffer from short-term memory loss, or some form of graph dyslexia...

**Comment by martin-henz** [comment]
I have the same problem. I often rely on screen shots as an attainable substitute for photographic memory.
