### ISSUE TITLE
Chapter 5: continue register rendered bold in JavaScript highlighting on the web

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#301]
JAVASCRIPTINLINE renders 

continue

in bold because this is a JavaScript keyword.

Maybe SCHEMEINLINE will work here, or
<LATEXINLINE>$\texttt{continue}$</LATEXINLINE>

**Comment by TobiasWrigstad** [comment]
I have fixed this in the PDF version of the book.
