### ISSUE TITLE
SVGPDF in PDF: text is squished

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#312]
<img width="589" alt="Screenshot 2020-07-11 at 2 46 11 PM" src="https://user-images.githubusercontent.com/30220768/87218448-5f96b380-c385-11ea-9c04-37084c2cf69c.png">

The web version is fine; seems that the text is somehow squished to fit into a bounding box?

Similar problem:

<img width="761" alt="Screenshot 2020-07-12 at 12 15 11 PM" src="https://user-images.githubusercontent.com/30220768/87238775-7860a100-c439-11ea-943e-79ee63aed727.png">

Similar problem:

<img width="761" alt="Screenshot 2020-07-12 at 12 37 01 PM" src="https://user-images.githubusercontent.com/30220768/87239008-78ae6b80-c43c-11ea-8d38-ef7f72551c65.png">

Similar problem:

<img width="739" alt="Screenshot 2020-07-12 at 12 49 03 PM" src="https://user-images.githubusercontent.com/30220768/87239141-2a9a6780-c43e-11ea-81d2-a8f633e73aaf.png">

Indices of S are squished:

<img width="739" alt="Screenshot 2020-07-12 at 1 15 15 PM" src="https://user-images.githubusercontent.com/30220768/87239445-cda0b080-c441-11ea-892b-3c34679a77a1.png">

Boxes overflowing:

<img width="763" alt="Screenshot 2020-07-12 at 3 16 26 PM" src="https://user-images.githubusercontent.com/30220768/87241149-c209b580-c452-11ea-9809-f1eaa5992f89.png">

Text clobbered:

<img width="680" alt="Screenshot 2020-07-12 at 4 02 48 PM" src="https://user-images.githubusercontent.com/30220768/87241810-3ba4a200-c459-11ea-91ba-9fa1aeeb9572.png">

**Comment by TobiasWrigstad** [comment]
Except for the first 2 which are bounding box errors (now fixed), this seems to be a font issue. Do you have the Libertine font installed on the machine where you are viewing this? 

I am not saying the error is in your machine -- just trying to identify what it is because on my side these all look fine! 

One possible way forward is to convert the text to shapes but that makes them harder to edit.

**Comment by TobiasWrigstad** [comment]
Resolved with the "canonical PDFs" with the fonts embedded
