### ISSUE TITLE
SVGPDF: design issues

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#314]
SICP JS has:

<img width="761" alt="Screenshot 2020-07-12 at 12 41 16 PM" src="https://user-images.githubusercontent.com/30220768/87239059-333e6e00-c43d-11ea-815f-757befc428bf.png">

and SICP Scheme has:

<img width="478" alt="Screenshot 2020-07-12 at 12 42 00 PM" src="https://user-images.githubusercontent.com/30220768/87239064-3c2f3f80-c43d-11ea-8bb2-05d7ff73cd46.png">

SICP is better because the processing is more consistently from left to right.

A similar issue:

<img width="784" alt="Screenshot 2020-07-12 at 12 46 17 PM" src="https://user-images.githubusercontent.com/30220768/87239110-cecfde80-c43d-11ea-85b0-6754dadae90e.png">

vs

<img width="665" alt="Screenshot 2020-07-12 at 12 46 50 PM" src="https://user-images.githubusercontent.com/30220768/87239112-d2fbfc00-c43d-11ea-9ce6-55dd738652d3.png">

This figure has unnecessary space between the two rows:

<img width="739" alt="Screenshot 2020-07-12 at 1 53 28 PM" src="https://user-images.githubusercontent.com/30220768/87239932-2fafe480-c447-11ea-8ed6-653c17dec225.png">

Similar this one:

<img width="739" alt="Screenshot 2020-07-12 at 2 09 39 PM" src="https://user-images.githubusercontent.com/30220768/87240126-6be44480-c449-11ea-8a74-893bdaef724b.png">

Similar this one:

<img width="718" alt="Screenshot 2020-07-12 at 5 08 58 PM" src="https://user-images.githubusercontent.com/30220768/87242783-7fe87000-c462-11ea-8f35-af0904f0f526.png">

The input arrow should come from the left, not from below:

<img width="761" alt="Screenshot 2020-07-12 at 4 00 21 PM" src="https://user-images.githubusercontent.com/30220768/87241762-d0f36680-c458-11ea-933c-f18c6d89279e.png">

here is the original:

<img width="556" alt="Screenshot 2020-07-12 at 4 00 59 PM" src="https://user-images.githubusercontent.com/30220768/87241774-ea94ae00-c458-11ea-88db-afcd370f9f19.png">

**Comment by TobiasWrigstad** [comment]
I've addressed the "unnecessary space between the rows" ones and pushed.

**Comment by TobiasWrigstad** [comment]
Fixed
