### ISSUE TITLE
SVGPDF: typos

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#315]
<img width="763" alt="Screenshot 2020-07-12 at 3 22 35 PM" src="https://user-images.githubusercontent.com/30220768/87241248-ab179300-c453-11ea-9b57-c699ce1a18b1.png">

should say "assign" instead of "set!" in two places.

<img width="718" alt="Screenshot 2020-07-12 at 4 59 22 PM" src="https://user-images.githubusercontent.com/30220768/87242653-4d8a4300-c461-11ea-9663-1005ca40062b.png">

semicolon missing in return statement: should be "body: return x * x;"

<img width="718" alt="Screenshot 2020-07-12 at 10 22 42 PM" src="https://user-images.githubusercontent.com/30220768/87248809-4e859980-c48e-11ea-9959-8369f2d2bd88.png">

Should say "Function" instead of "Procedure". Also perhaps "Evaluate" instead of "Eval"?

**Comment by TobiasWrigstad** [comment]
Wrt Fig 3.29, the problem seems we are using the Scheme figure and not the JavaScript one. The JAvaScript figure uses "update" and not "assign". Should I change to assign?

**Comment by TobiasWrigstad** [comment]
Other figures fixed and pushed. Not marking this as resolved yet because of the above.

**Comment by TobiasWrigstad** [comment]
Marking this as resolved.
