### ISSUE TITLE
5.5: inconsistencies

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#316]
(1)

Section 5.5.6 needs to refer to and probably make use of scan_out_declarations in 4.1.1.

(2)

lookup_name_value needs to be renamed to lookup_symbol_value.

**Comment by TobiasWrigstad** [comment]
> lookup_name_value needs to be renamed to lookup_symbol_value
Do you mean `loookup_variable_value`? I looked briefly for `lookup_name_value` even in old commits but failed.

**Comment by TobiasWrigstad** [comment]
> Section 5.5.6 needs to refer to and probably make use of scan_out_declarations in 4.1.1.

OK. I haven't yet made any executable code for lexical addressing.

**Comment by TobiasWrigstad** [comment]
When we spoke yesterday, you said you would take a stab at 5.5.6. Just checking that this is still in the books given I'm assigned here.

**Comment by martin-henz** [comment]
Yes, I'll continue with 5.5. Hoping to have a working compiler in a few days time.
