### ISSUE TITLE
5.3: Add footnote on labels in assign instructions

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#322]
It seems that 5.3.2 introduces the practice of using labels in assign and using registers in go_to. This deviates from 5.1.5, so perhaps a footnote would be in place.

(5.4 of course relies heavily on labels being used that way, with the continue register.)

**Comment by TobiasWrigstad** [comment]
In the spirit of the project, maybe we should not do this as this is consistent with SICP 2e which also does this "under the covers" so to speak.

**Comment by martin-henz** [comment]
ok
