### ISSUE TITLE
1.3.1: TeX code visible in text

### ISSUE THREAD

**Issue by tfritzon** [source-academy/sicp#325]
Here: https://source-academy.github.io/sicp/split/chapters/1.3.2.html#p8

**Comment by martin-henz** [comment]
Yea, the orange-coded segments may have LaTeX, which is to be expected for the PDF-only version, and we take the liberty to use LaTeX beyond what MathJax can support. I've added the following in a PR, please review @tfritzon 

<img width="426" alt="Screenshot 2020-07-16 at 10 35 30 AM" src="https://user-images.githubusercontent.com/30220768/87620287-bff46f00-c750-11ea-8e14-6a1d08663e53.png">
