### ISSUE TITLE
4.1.5: eval is not allowed

### ISSUE THREAD

**Issue by tfritzon** [source-academy/sicp#328]
The text about eval: https://source-academy.github.io/sicp/split/chapters/4.1.5.html#p8
should probably say something about eval being blocked (in js-lang) because of security reasons and are generally frowned upon.

**Comment by martin-henz** [comment]
See footnote [5] after the sentence. This takes care of it, right? Or do you think the issue requires mentioning in the text? @tfritzon

**Comment by tfritzon** [comment]
I missed that. Yes, that clears it up.
