### ISSUE TITLE
CH1-4 BUG: Minor Typos visible on textbook.

### ISSUE THREAD

**Issue by travisryte** [source-academy/sicp#334]
- [x]  all other words use behavior, but this uses behaviour, to standardise. (https://github.com/travisryte/sicp/blob/master/xml/chapter4/section1/subsection2.xml#L1582)

- [x] excercises should remove the c (https://github.com/travisryte/sicp/blob/master/xml/chapter1/section2/subsection1.xml#L497)

- [x] **preceeded**  should be => preceded
 (https://github.com/travisryte/sicp/blob/master/xml/chapter1/section1/subsection2.xml#L122) 

- [x] appoximations should be approximations (https://github.com/travisryte/sicp/blob/master/xml/chapter2/section1/subsection4.xml#L706)

- [x] ompiled is missing a c (https://github.com/travisryte/sicp/blob/master/xml/chapter5/section5/subsection7.xml#L673)

- [x] witout missing a h (https://github.com/travisryte/sicp/blob/master/xml/chapter4/section4/subsection1.xml#L92)

- [x]  Tnhe should be The, 3.3.4 line 1358 (https://github.com/travisryte/sicp/blob/master/xml/chapter3/section3/subsection4.xml#L1348)

- [x]  strem should be stream (https://github.com/travisryte/sicp/blob/master/xml/chapter3/section5/subsection1.xml#L170)

- [x] inital should be initial (https://github.com/travisryte/sicp/blob/master/xml/chapter2/section3/subsection4.xml#L180)

- [x] ecoding should be encoding (https://github.com/travisryte/sicp/blob/master/xml/chapter2/section3/subsection4.xml#L180)

Fixing these typos will give the textbook a more professional feel. @martin-henz shall i make a PR?

**Comment by travisryte** [comment]
[standardise behavior to behaviour, or vice versa, there are 2 versions](https://github.com/travisryte/sicp/blob/919c9e8a46f18a1e5cdcee8675b0076ea90e18f5/xml/chapter4/section1/subsection2.xml#L1582)

**Comment by travisryte** [comment]
[compiled is missing a c](https://github.com/travisryte/sicp/blob/919c9e8a46f18a1e5cdcee8675b0076ea90e18f5/xml/chapter5/section5/subsection7.xml#L673)

**Comment by travisryte** [comment]
[witout should be without](https://github.com/travisryte/sicp/blob/919c9e8a46f18a1e5cdcee8675b0076ea90e18f5/xml/chapter4/section4/subsection1.xml#L92)

**Comment by travisryte** [comment]
[appoximations should be approximations](https://github.com/travisryte/sicp/blob/919c9e8a46f18a1e5cdcee8675b0076ea90e18f5/xml/chapter2/section1/subsection4.xml#L706)

**Comment by travisryte** [comment]
[excercises should remove the c](https://github.com/travisryte/sicp/blob/master/xml/chapter1/section2/subsection1.xml#L497)

**Comment by martin-henz** [comment]
According to https://github.com/source-academy/sicp/issues/249 this will earn you S$100 in Starbucks coffee vouchers. (after verification) Do you like coffee or would you like some other sort of voucher with some other food or drink outlet? @travisryte

**Comment by travisryte** [comment]
Wow a $100 voucher, that's quite a lot for an hour of work 🤣. HAHAHA. I am ok with a $10 voucher.
May I request a Grabfood voucher instead? Given the current situation in NUS, I won't be able to access Starbucks. 😫

**Comment by martin-henz** [comment]
Promise is promise. Just sent you the Grabfood voucher. Let me know if you don't receive it soon.

**Comment by travisryte** [comment]
Thank you Prof!
