### ISSUE TITLE
PDF edition: Syntax highlighting in SNIPPETS with LATEX="yes"

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#344]
Keywords are not highlighted

**Comment by TobiasWrigstad** [comment]
![image](https://user-images.githubusercontent.com/364888/88601135-4b82cf80-d070-11ea-8480-03d2283b8bd2.png)

I don't think this is universal. The screenshot suggests otherwise. Maybe it depends on the LaTeX code in the figure.

**Comment by gerhean** [comment]
Syntax highlighting in SNIPPETS seem to be correct and consistent based purely on what I can see in the online pdf version. Is it possible to showcase an example where it is not working?
