### ISSUE TITLE
Web edition: exercises referring to footnotes

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#346]
For example, the footnote reference in exercise 4.9 should go to footnote 4 and not footnote 2:
http://localhost:8080/chapters/4.1.2.html#ex_4.9

**Comment by TobiasWrigstad** [comment]
It seems the cause of this bug is due to a confusion of different counters. The 4th footnote in §4.1.1 is the 2nd one with a label. Adding a label to e.g. the 1st unlabelled footnote makes the footnote above go to the 3rd footnote in §4.1.1.
