### ISSUE TITLE
WEB: 2.5.3 - Part of exercise 2.91 is not render correctly

### ISSUE THREAD

**Issue by Reki-code** [source-academy/sicp#352]
There are two lines of LaTeX in the javascript snippet of exercise 2.19 that cannot be rendered correctly in the web version
https://github.com/source-academy/sicp/blob/53626789f39e158781fea7006e9cf66b3d4d9429/xml/chapter2/section5/subsection3.xml#L1139-L1140
Those that are not in exercise can render correctly, maybe latex cannot be rendered correctly in the EXERCISE tag
https://github.com/source-academy/sicp/blob/53626789f39e158781fea7006e9cf66b3d4d9429/xml/chapter2/section5/subsection3.xml#L265-L267

**Comment by martin-henz** [comment]
this is good now
