### ISSUE TITLE
5.4: inconsistencies

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#356]
* ~~Program snippets are not consistent with the actual implementations in 5.4.4~~

* ~~Replace "exp" with "stmt"~~

* ~~5.4.1: "The function compound_apply is the only place in the interpreter where the env register is ever assigned a new value." 
not true: blocks do that too~~

* ~~rename "ev_if" to "ev_cond"~~

* ~~5.4.3:  "ev_variable_declaration_1" and "ev_constant_declaration_1" should return undefined and not "ok".~~

* ~~replace the term "operand" with "argument expression" and "operator" with "function expression"~~

* ~~The hard-wiring of the block creation in the code of 5.4.4 is a hack. To get a proper interactive REPL, we should do it as in the new driver_loop of 4.1.4 and the new compile_and_go of 5.5.7: The read_eval_print subroutine should scan out the declared names and extend the current program environment (obtained by get_environment), by bindings of the names to "*unassigned*", and then set the program environment to the result (using set_environment). See the prelude of compile_and_go in 5.5.7.~~

* ~~Exercises 5.23 and 5.24 need replacement~~

* ~~What to do with the "Regrettably..." footnote in 5.4.4?~~

**Comment by TobiasWrigstad** [comment]
> Exercises 5.23 and 5.24 need replacement

I propose to change them to add support for `if (...) { ... } else { ... }` statements, first assuming there is no return statement in the then- or else-blocks (5.23) and then adding support for returning from within such blocks (5.24).

**Comment by martin-henz** [comment]
> > Exercises 5.23 and 5.24 need replacement
> 
> I propose to change them to add support for `if (...) { ... } else { ... }` statements, first assuming there is no return statement in the then- or else-blocks (5.23) and then adding support for returning from within such blocks (5.24).

Or maybe a bit more interesting: while loops: 5.23 using translation to function applications with a 'cheat' similar to the original 5.23, and 5.23 by running a proper machine-level loop, with proper handling of break; and continue; with reference to exercise 4.7 (4.1.2).
