### ISSUE TITLE
CH1-4 BUG: Section 4.3.2 - Missing quotes around string value in expected program output

### ISSUE THREAD

**Issue by anubh-v** [source-academy/sicp#357]
![image](https://user-images.githubusercontent.com/35621759/88696192-84d14300-d135-11ea-88b4-ae02e0307521.png)

The string `professor` should have quotes --> `"professor"`

Link to source file: https://github.com/source-academy/sicp/blob/58134abfa0b25fe104272bf393058e543481d985/xml/chapter4/section3/subsection2.xml#L879

**Comment by martin-henz** [comment]
That's great! This earns you a starbucks coffee voucher. Also grab food voucher possible. I'll be in touch about your preference!
