### ISSUE TITLE
PDF: clickable programs?

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#37]
Can we turn programs in the PDF version into clickable links, similar to programs in the web version?

**Comment by gerhean** [comment]
I'm not sure how to generate the url with the right code for source academy

**Comment by martin-henz** [comment]
See here how Liu Hang did it in Ruby:
rails/app/controllers/chapters_controller.rb

Look for "compressToEncodedURIComponent".

**Comment by gerhean** [comment]
Should be done. Please inform me of bugs.
