### ISSUE TITLE
PDF: Extra vertical space in 1.1

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#380]
<img width="497" alt="Screenshot 2020-08-31 at 2 53 37 PM" src="https://user-images.githubusercontent.com/30220768/91691126-afca0f00-eb99-11ea-925d-1b4620e816bd.png">

Note the extra line after the second item.

**Comment by gerhean** [comment]
Problem is that in:
```
by which compound elements are built from simpler ones, and \index{means of combination}%
 \index{combination, means of}%
```
there is a space between `and` and `\index{means of combination}`.

Removing that space makes the output correct.

![image](https://user-images.githubusercontent.com/16630400/91787993-b14d1300-ec3d-11ea-9f7c-b84408ec07e4.png)

Not sure why this happens, but I'll try looking into how it might be fixed.

**Comment by martin-henz** [comment]
Thanks for checking. You will notice that I've tried to clean up spurious spaces, but this one is a bit resistant to my efforts.

**Comment by gerhean** [comment]
Was able to fix by adding these lines:
```
// Removes a space directly before an index.
    if (writeTo.slice(-1)?.[0]?.slice(-1) == " ") {
      writeTo[writeTo.length - 1] = writeTo[writeTo.length - 1].slice(0, -1);
    }
```

here:
![image](https://user-images.githubusercontent.com/16630400/91790997-a0ec6680-ec44-11ea-8745-f6d767e1ff46.png)

However I'm not sure if it will cause something to break somewhere else.

**Comment by martin-henz** [comment]
OK, will try this. Thanks!

**Comment by martin-henz** [comment]
That's too "aggressive". We now have many words fused together when they are only separated by an index entry.

Let's observe how often this appears and maybe we have a manual fix in the end.

**Comment by gerhean** [comment]
Would removing the % behind the `index{}` solve the problem without breaking anything?

**Comment by gerhean** [comment]
Actually it doesnt work properly

**Comment by gerhean** [comment]
Possible fix?

Don't add strings with only spaces (not sure why it was commented out however so might break something).

```
else if (!trimedValue.match(/^ *$/)) {
      writeTo.push(trimedValue);
    }
```
![image](https://user-images.githubusercontent.com/16630400/91813419-3dbefc00-ec65-11ea-9fc8-e6b52236e8e5.png)


Then we can add a space to behind every `\index{}`, which any subsequent `\index` would just remove:

![image](https://user-images.githubusercontent.com/16630400/91813452-4d3e4500-ec65-11ea-8b65-e7845d270a50.png)

**Comment by TobiasWrigstad** [comment]
Unless this creeps up too many times, it seems the simplest solution is to reformat the XML sources to avoid white spaces between prose and INDEX entries, and between INDEX entries themselves where needed.
