### ISSUE TITLE
PUBLIC PDF: section numbers in running heads are off-by-one in many places

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#385]

**Comment by martin-henz** [comment]
There are also running heads with "xxx.0":

<img width="426" alt="Screenshot 2020-09-07 at 11 29 27 AM" src="https://user-images.githubusercontent.com/30220768/92345801-63348580-f0fd-11ea-8178-ab89c13fd0a0.png">

**Comment by martin-henz** [comment]
From Julie:

Sometimes the subsection number in a running head ends with .0 !!

I'm not going to flip through the whole book, but here are 3 instances
and a theory of a pattern that abstracts those 3 instances.
This is in the pdf currently posted, generated on 2020-08-25.

p.255, last page of 3.1.3, says 3.1.0
p.273, last page of 3.2.4, says 3.2.0
p.565, last page of 5.2.4, says 5.2.0

Pattern seems to be:
if subsection ends on a right-hand page (e.g., 3.1.3 on p.255)
&& top of next page is start of a new section (e.g., 3.2 on p.256
then label last page of subsection with ....0
else label it correctly

**Comment by martin-henz** [comment]
This is fixed in MIT-Press-version, right? If yes, we can re-label this issue to "Public PDF".
@TobiasWrigstad

**Comment by TobiasWrigstad** [comment]
Yes!
