### ISSUE TITLE
PDF: Figure 2.12 needs work

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#387]
<img width="895" alt="Screenshot 2020-09-06 at 10 22 57 PM" src="https://user-images.githubusercontent.com/30220768/92327901-7f99d900-f08f-11ea-9eaf-0f033e139990.png">

**Comment by TobiasWrigstad** [comment]
I fear this runs into major problems: we do not support two different code blocks on the same line. 

One way to handle this ofc is to simply move up the 2nd line `const wave4 = ...` on the same line as the first and add some extra white space between the figures. Maybe this is what is intended? @martin-henz

**Comment by martin-henz** [comment]
Yes, for sure. Some hack with white space, and (if needed) using PDF_ONLY or MITPRESS_ONLY.

**Comment by TobiasWrigstad** [comment]
Great, then I'll close this one tomorrow.
