### ISSUE TITLE
PDF: spurious letter in footnote

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#389]
<img width="423" alt="Screenshot 2020-09-07 at 9 38 19 AM" src="https://user-images.githubusercontent.com/30220768/92340710-02ea1780-f0ee-11ea-8528-1ff877bb5e5e.png">

The "d." is not in the original LaTeX!

**Comment by martin-henz** [comment]
<img width="423" alt="Screenshot 2020-09-07 at 9 57 07 AM" src="https://user-images.githubusercontent.com/30220768/92341495-80168c00-f0f0-11ea-80d3-c1069ec68078.png">

This time a "b." !

**Comment by TobiasWrigstad** [comment]
This one is still illusive! I just spent 30 minutes on this without understanding what is going on. It seems that whatever environment is added in these positions, some label is added. I've dug through the code of quote before coming to the conclusion that the problem is not there.

**Comment by TobiasWrigstad** [comment]
![image](https://user-images.githubusercontent.com/364888/98750498-69c1d080-23be-11eb-979f-5096c29b9b54.png)
This is what is produced by adding an empty `\begin{center}\end{center}` in the footnote.

**Comment by TobiasWrigstad** [comment]
OK, some kind of breakthrough! When removing `[\alph*.]` from an enumerate on an earlier page, the `d.` changed to a `4.`. So I know where to continue tomorrow.

**Comment by TobiasWrigstad** [comment]
The code that produces the error is inside the answer text which is not rendered. That code is well-formed. So might be a bug in LaTeX's box handling.

**Comment by TobiasWrigstad** [comment]
![image](https://user-images.githubusercontent.com/364888/98751412-53b50f80-23c0-11eb-880c-3953fa0a40a7.png)
Saving this here for later reference.

**Comment by martin-henz** [comment]
Seems fixed now. @TobiasWrigstad can we close this?

**Comment by TobiasWrigstad** [comment]
Yeah, let's!
