### ISSUE TITLE
PDF: listings escape issue in Section 1.1.4

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#39]
The ^ character is an escape character in the `listings` package. This leads to a formating problem in section 1.1.4:

<img width="738" alt="Screenshot 2019-06-04 at 5 47 14 PM" src="https://user-images.githubusercontent.com/30220768/58869653-3bcc5d00-86f1-11e9-938a-f3ce332c4c20.png">

**Comment by martin-henz** [comment]
Similar case in section 1.3.2:

<img width="774" alt="Screenshot 2019-06-05 at 4 49 32 PM" src="https://user-images.githubusercontent.com/30220768/58943281-ffad0100-87b1-11e9-9003-e62ab18bb314.png">

**Comment by gerhean** [comment]
fixed
