### ISSUE TITLE
PDF: first paragraph of each chapter is indented

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#391]
but should not be indented:

<img width="358" alt="Screenshot 2020-09-07 at 12 30 25 PM" src="https://user-images.githubusercontent.com/30220768/92348529-f376c880-f105-11ea-9c15-3de919ffcb1b.png">

**Comment by TobiasWrigstad** [comment]
This seems to have been resolved already

**Comment by martin-henz** [comment]
Yes, fixed this manually, by adding a <NOINDENT/> tag to XML. Ugly? Yes, but the tag comes in handy elsewhere too.
