### ISSUE TITLE
PDF: four different font sizes for programs

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#392]

**Comment by martin-henz** [comment]
Re-opening this: Here is what Julie says:

\def\normalcodesize{\fontsize{9.8}{11pt}\selectfont}
\def\exercisecodesize{\fontsize{9}{10pt}\selectfont}
\def\figurecodesize{\fontsize{8.7}{10pt}\selectfont}
\def\footnotecodesize{\fontsize{8}{9pt}\selectfont}

(where the numbers are to be ignored, except that they indicate roughly the relative sizes)

**Comment by TobiasWrigstad** [comment]
Adding these in. Will have to modify the code generation to insert the appropriate size depending on where processing of a node takes place. Hope to have done by Thursday.
