### ISSUE TITLE
Infinite scrolling does not stop for Making-of

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/sicp#4]
The infinite scrolling for [_JavaScript Adaptation Making-of_](https://www.comp.nus.edu.sg/~cs1101s/sicp/chapters/122) does not end. Rather, it keeps rendering copies of _Preface of JavaScript Adaptation_. 

Tested on 
- Chrome 66 for Mac and 
- Chrome 67.0.3396.87 (Official Build) (64-bit) for debian

<div align="center">
<img src="https://thumbs.gfycat.com/OrderlyAffectionateIndiancow-size_restricted.gif"/>
</div>

**Comment by martin-henz** [comment]
Piaopiao fixed this.
