### ISSUE TITLE
PDF: extra space between number and heading text

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#40]
There seems to be some extra space between the number of a heading and its text. This becomes apparent if the text does not fit into one line. Example:

<img width="749" alt="Screenshot 2019-06-04 at 9 15 23 PM" src="https://user-images.githubusercontent.com/30220768/58882181-4517f280-870e-11e9-837d-d3f1975fd4c4.png">

**Comment by gerhean** [comment]
Fixed

**Comment by gerhean** [comment]
fixed
