### ISSUE TITLE
PDF: programs over two pages

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#406]
programs should never be broken by page breaks

**Comment by TobiasWrigstad** [comment]
Closing this. Currently, we allow programs to be split over two pages at top-level function declarations, so 
```
function foo() {
  ...
}
function bar() {
  ...
} 
```
will be inserted in the LaTeX document as:
```
function foo() {
  ...
}
```
_some spacing which allows a pagebreak_
```
function bar() {
  ...
} 
```
There is also a `<ALLOW_BREAK/>` tag that can be used to allow breaks at other places. 
I am closing this issue as it pertained to the idiosynchrasies of the "unformatted" master branch.
