### ISSUE TITLE
2.5.2: Figure 2.25 weird size

### ISSUE THREAD

**Issue by Rye-Catcher** [source-academy/sicp#409]
On my Chrome (Version 85.0.4183.121 (Official Build) (64-bit)), the **figure 2.25** in the e-book looks really big

![figure 2 25](https://user-images.githubusercontent.com/35390703/95135836-a1be6e00-0797-11eb-8703-6204ce403e33.png)

(This is 25% zoom)

**Comment by martin-henz** [comment]
ebook no longer supported
