### ISSUE TITLE
PDF: Formatting of exercises

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#41]
Exercises are currently formatted like this:

<img width="717" alt="Screenshot 2019-06-04 at 9 30 41 PM" src="https://user-images.githubusercontent.com/30220768/58933714-c917bc00-879a-11e9-88b7-5045e69d0fab.png">

A couple of suggestions:

(1) Spacing

In the original textbook, exercises look like this:

<img width="749" alt="Screenshot 2019-06-04 at 9 30 25 PM copy 2" src="https://user-images.githubusercontent.com/30220768/58933777-ee0c2f00-879a-11e9-96d2-586535e92b8b.png">

I think this spacing is nicer: "Exercise" flushed left and no vertical space between "Exercise" and the text.

(2) Link to solution

I find the text "Link to solution" at the top a bit clumsy. How about just letting the users click on "Exercise 1.7" instead?

<img width="749" alt="Screenshot 2019-06-04 at 9 30 25 PM copy" src="https://user-images.githubusercontent.com/30220768/58933890-46dbc780-879b-11e9-9454-5505763a3488.png">

Would that be too obscure?

Alternatively, we could provide a link at the bottom:

<img width="749" alt="Screenshot 2019-06-04 at 9 30 25 PM copy 2" src="https://user-images.githubusercontent.com/30220768/58933970-902c1700-879b-11e9-9781-b64ba6096bf1.png">

**Comment by gerhean** [comment]
Provided a link at the bottom

**Comment by martin-henz** [comment]
The link at the bottom may sometimes go to the next page, which is not so desirable. Example:

<img width="491" alt="Screenshot 2019-06-06 at 5 12 45 PM" src="https://user-images.githubusercontent.com/30220768/59021449-65ff5580-887e-11e9-9cf7-c7c8fbd31594.png">

LaTeX is quite powerful for such things. For example, you could add
```\hfill Solution```
to make sure that "Solution" is flushed to the right.

**Comment by gerhean** [comment]
solution link should be like in example image now

**Comment by gerhean** [comment]
done

**Comment by martin-henz** [comment]
Oh, yes. We abandoned the links to the solutions in the PDF when we prepared the MIT Press print edition. At the moment, we only generate the official print edition (or something close to that, with bug fixes and minor improvements). Feel free to revive a version that has solutions. Would be nice, eventually as a companion for teachers.
