### ISSUE TITLE
EPUB: Dead link to epub version

### ISSUE THREAD

**Issue by marcolussetti** [source-academy/sicp#414]
The link on the homepage pointing to the ebook/epub version is dead:
![image](https://user-images.githubusercontent.com/15794684/97382826-7e17b080-1889-11eb-8513-be67ea4c50c1.png)

This points to https://source-academy.github.io/sicp/sicpjs.epub which is dead/missing:
![image](https://user-images.githubusercontent.com/15794684/97382777-5f191e80-1889-11eb-9429-9bab8fd317aa.png)

**Comment by marcolussetti** [comment]
Looks like this is related to https://github.com/source-academy/sicp/commit/27203a4abb1121e4d32c45e8008c2f5bec296301 probably -- wondering if perhaps an older epub could be at least included on the website?

**Comment by martin-henz** [comment]
Sorry we currently don't support epub and don't distribute outdated versions of SICP JS.
