### ISSUE TITLE
PDF: HIDE directive currently ignored

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#42]
The option ` <SNIPPET HIDE="yes">` is currently ignored. This leads to many extra program snippets appearing in the text, for example:

<img width="717" alt="Screenshot 2019-06-04 at 9 30 41 PM copy" src="https://user-images.githubusercontent.com/30220768/58934235-6f17f600-879c-11e9-841e-980bb01af486.png">

**Comment by gerhean** [comment]
Fixed
