### ISSUE TITLE
3.5.4: Update footnote to discuss generic types

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#420]
The last footnote in 3.5.4 is an embarrassment from today's perspective; programming languages have come a long way since then. @TobiasWrigstad can you update the footnote?

<img width="816" alt="Screenshot 2020-11-11 at 6 06 53 PM" src="https://user-images.githubusercontent.com/30220768/98798558-f87b2f80-2448-11eb-8896-0f540ced90f2.png">

**Comment by TobiasWrigstad** [comment]
Good catch. Indeed I will!

**Comment by martin-henz** [comment]
Resolved by Julie on 14/5 via email: Subject: Footnote in 3.5.4 on parametric polymophism
