### ISSUE TITLE
PDF: Fix 1.1.4 and 1.3.2: vertical arrows displaced

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#423]
After fixing the fonts, we need to manually adjust the distances between the vertical arrows in the explanations of function declaration and lambda expression.

<img width="736" alt="Screenshot 2020-11-16 at 9 57 52 PM" src="https://user-images.githubusercontent.com/30220768/99260774-cc035100-2856-11eb-8cb0-e46cf6a0c2f0.png">

<img width="736" alt="Screenshot 2020-11-16 at 9 57 13 PM" src="https://user-images.githubusercontent.com/30220768/99260714-b726bd80-2856-11eb-88f3-5d417af106dc.png">

**Comment by TobiasWrigstad** [comment]
Fixed in the formatted builds in a way that automatically rescales with any font change. Closing.
