### ISSUE TITLE
PDF: size of images

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#43]
We need to find a way to have reasonable sizes for the images. Do they have a "natural" size that we can use for all versions of the textbook?

Currently, the PDF version stretches images to fill the entire width of the text:

<img width="694" alt="Screenshot 2019-06-05 at 2 18 28 PM" src="https://user-images.githubusercontent.com/30220768/58934415-ffeed180-879c-11e9-9048-18db6be43820.png">

**Comment by gerhean** [comment]
fixed
