### ISSUE TITLE
Public PDF: 4.1.2 fontsizes

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#442]
Check the font sizes in the parser rules. Maybe all right-hand-sides can be onlines?

**Comment by martin-henz** [comment]
Is this done already? @TobiasWrigstad

**Comment by martin-henz** [comment]
In public PDF, the equations are too small in this section. MIT-Press version is ok.

**Comment by TobiasWrigstad** [comment]
I think we can close this. When we merge the two branches, this will be taken care of.
