### ISSUE TITLE
PDF: white space between SPLITINLINE currently ignored

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#45]
The XML in section 1.2.6
```
            The 
            <SPLITINLINE>
              <SCHEME>
                <SCHEMEINLINE>smallest-divisor</SCHEMEINLINE> 
              </SCHEME>
              <JAVASCRIPT>
                <JAVASCRIPTINLINE>smallest_divisor</JAVASCRIPTINLINE> 
              </JAVASCRIPT>
            </SPLITINLINE>
            <SPLITINLINE><SCHEME>procedure</SCHEME><JAVASCRIPT>function</JAVASCRIPT></SPLITINLINE> 
            shown
```
is currently rendered as follows:

<img width="313" alt="Screenshot 2019-06-05 at 4 44 30 PM" src="https://user-images.githubusercontent.com/30220768/58942901-3fbfb400-87b1-11e9-87d8-6d4729233aa3.png">

There is no space between `smallest_divisor` and "shown", although there is a newline between the two occurrences of `SPLITINLINE`.

**Comment by gerhean** [comment]
Should be fixed
