### ISSUE TITLE
Change all eqnarray* for align*

### ISSUE THREAD

**Issue by TobiasWrigstad** [source-academy/sicp#451]

**Comment by martin-henz** [comment]
Do you mean
Change all eqnarray* into align*
or
Change all eqnarray* instead of align*
?
@TobiasWrigstad

**Comment by TobiasWrigstad** [comment]
Change all eqnarray* into align*

This is mostly done in the formatted version. So when we merge the branches this will be solved.

**Comment by TobiasWrigstad** [comment]
This is solved in the formatted version as of 5 minutes ago. Marking as resolved.
