### ISSUE TITLE
PDF: space before heading missing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#464]
(MIT-formatted version):

<img width="556" alt="Screenshot 2021-04-23 at 8 13 01 AM" src="https://user-images.githubusercontent.com/30220768/115799894-fe1f6d00-a40b-11eb-8b21-4b39772c2b29.png">

**Comment by TobiasWrigstad** [comment]
Fixed in f53f2df and will close automatically when merged with master
