### ISSUE TITLE
PDF: indentation of snippets in exercises with subexercises

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#478]
<img width="478" alt="Screenshot 2021-05-16 at 3 54 07 PM" src="https://user-images.githubusercontent.com/30220768/118389950-0bbcc100-b65f-11eb-9a2d-508ee0d68427.png">

**Comment by TobiasWrigstad** [comment]
Thanks. Julie also pointed these out. I've struggled with these ones but I haven't been able to find the reason for this indentation yet! 

I should have recorded this issue. Thanks for doing so.

**Comment by martin-henz** [comment]
ok. just making sure it's on the record. the issues are fewer and fewer. exciting.

**Comment by TobiasWrigstad** [comment]
Indeed!
