### ISSUE TITLE
SVG: integral in figure 3.33 missing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#481]
<img width="478" alt="Screenshot 2021-05-19 at 8 16 05 AM" src="https://user-images.githubusercontent.com/30220768/118738839-9299b580-b87a-11eb-95b4-10a17aaf38e8.png">

**Comment by TobiasWrigstad** [comment]
This is a regression! I have fixed this one before. Did you change the fonts of this figure?

**Comment by TobiasWrigstad** [comment]
![image](https://user-images.githubusercontent.com/364888/118894022-bbb25880-b903-11eb-93ac-28d1c773e84a.png)
Weird! The integral sign shows up on my side. Both in the diagrams PR and in current master.

**Comment by martin-henz** [comment]
This is a bug in my MacOS Preview tool: Adobe Reader shows the proper integral sign, and so does Chrome's embedded PDF viewer. The problem arises when I look at the file using Preview, regardless of whether I download the PDF from github or whether I generate the file.

We can safely close this issue.

**Comment by TobiasWrigstad** [comment]
Phew! Good.
