### ISSUE TITLE
SVG: figure 1.2 doesn't look nice

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#482]
<img width="582" alt="Screenshot 2021-05-19 at 8 53 18 AM" src="https://user-images.githubusercontent.com/30220768/118740952-b6132f00-b87f-11eb-8f60-657b14049021.png">

There should be longer lines instead of the ascii slashes and backslashes.

**Comment by TobiasWrigstad** [comment]
How do you feel about this? 
![image](https://user-images.githubusercontent.com/364888/118894637-eea91c00-b904-11eb-9946-954c7774a9cb.png)

**Comment by martin-henz** [comment]
Nice, except that `improve` does not use `abs`.

**Comment by TobiasWrigstad** [comment]
Ah shoot. Well spotted. I'll fix that and commit.
