### ISSUE TITLE
PDF: caption line-breaking needs fine-tuning

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#487]
p.424, with the similar captions of figs 4.6 and 4.7,
looked better before

 In fig 3.12 need to prevent line break between "y:" and "list(...)"
(use a nonbreaking space or make "y: list(...)" into some nonbreakable
entity (e.g. mbox)

**Comment by TobiasWrigstad** [comment]
See PR #490

**Comment by martin-henz** [comment]
Dont know what Julie means by "looked better before". (maybe she means what I fixed in #513?)

The issue in fig 3.12 seems gone now.

Can we close this issue?
