### ISSUE TITLE
SVG: Figures 3.2 to 3.8 have issues (sections 3.2.1, 3.2.2)

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#495]
p.231
FIG 3.2 excess line spacing in function square
FIG 3.2 make global env wider so that "other...primitives" fits on line

p.215
FIG 3.4 excess line spacing in right-hand return expression

p.216
FIG 3.5 excess line spacing between lines of code in left two expressions

FIGS 3.6-3.8: 3 different spacings for the same IF expression

p.220
Fig 3.8 has brace cut off:
<img width="541" alt="Screenshot 2021-05-29 at 5 09 34 PM" src="https://user-images.githubusercontent.com/30220768/120064811-c48ff080-c0a0-11eb-8223-11166bb6ea99.png">

(julie email: Section 3.2 -- text, figures, ... )

**Comment by TobiasWrigstad** [comment]
On it!

**Comment by TobiasWrigstad** [comment]
Haha, the _FIG 3.5 excess line spacing between lines of code in left two expressions_ is a trick of the mind. The first one has the standard amount of line spacing, and the 2nd has *reduced* (by me earlier) spacing. The eye is fooled because of the almost only "low" characters. I'll fix this manually now.

**Comment by TobiasWrigstad** [comment]
You wrote:
> p.215
> FIG 3.4 excess line spacing in right-hand return expression

But the current figure is:
![image](https://user-images.githubusercontent.com/364888/120088048-46a60680-c0ed-11eb-8c91-51f72329f1cd.png)

I don't see a problem with the right-hand return expression. Again, this is a manual fix by me from earlier.

**Comment by TobiasWrigstad** [comment]
There is something super weird going on in inkscape. I sometimes are not allowed to change the line spacing, and there does not seem to be a consistent treatment across multiple files. I've tried to compensate manually and by measuring on the screen.

**Comment by TobiasWrigstad** [comment]
PR with review request made!
