### ISSUE TITLE
PDF: finalize type size

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#499]
We need to finalize the type sizes for everything, so that we can do the page-by-page work when the content is all settled.

**Comment by TobiasWrigstad** [comment]
Note: when this is done, we need to align all font sizes in all images with the chosen type size.

**Comment by martin-henz** [comment]
Not sure if that will be necessary. The font sizes currently seem a teeny bit too large in the images across the board, in my view. If the text font size increases a tiny bit, the image fonts may be just right. 

Just a personal hunch right now. Need to see how it looks of course.

**Comment by TobiasWrigstad** [comment]
Marking this as done. 

For the record: 

Main text: 10.8 over 13   --  inline code 10.6 over 13
Exercises: 10   over 12   --  inline code 9.5 over 12
Footnotes: 9.5   over 11   --  inline code 9 over 11

Code blocks (snippets) in main text:  9.8 over 11
Code blocks (snippets) in exercises:    9 over 11
Code blocks (snippets) in footnotes:    8 over 9

Code showing output is slanted but the size is the same.
