### ISSUE TITLE
PDF: spurious section number

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#50]
<img width="730" alt="Screenshot 2019-06-07 at 10 54 07 AM" src="https://user-images.githubusercontent.com/30220768/59078719-e66f9600-8912-11e9-9605-c90bc3f85ddb.png">

The link "1.2.6" appears in the footnote part of the page for no apparent reason.

**Comment by gerhean** [comment]
Footnote wasn't rendering properly here. After fixing other bugs, the text that was supposed to be above appeared, so I'm just gonna close this issue.
