### ISSUE TITLE
SVG: Figure 2.3 has extra spaces in the program

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#500]
To check and fix if necessary, see email from Julie:

from: | Julie Sussman&nbsp;&lt;jems@csail.mit.edu&gt;
-- | --
reply-to: | jems@alum.mit.edu
to: | Tobias Wrigstad &lt;tobias.wrigstad@it.uu.se&gt;
cc: | Martin Henz &lt;henz@comp.nus.edu.sg&gt;
date: | 13 Apr 2021, 02:49
subject: | Formatted figures (yay!!)

Figs
 2.3
~~3.2 function square
 3.4 rightmost RETURN
 3.5 sum_of_squares
     square(x) + square(y)
*3.6 8-line body!
*3.7 7-line body
*3.8 6-line exp~~

~~*5.7
(BUT code is fine in other chap.5 figures!)~~

~~--Also you might want to remove some whitespace from the bottom of
 3.5, 3.20, 3.21
 so the caption fits closer to the content of the figure~~

~~--Captions: Is the code in captions too large?
  3.13, 3.14, 3.15, 3.16, 3.17, 3.20, 3.32
  4.6, 4.7, 5.14, 5.17~~

--Fig 5.11 Slide the code over to the left for 2 reasons
  + get the "controller(" parenthesis away fromt the triangle
  + fit the comment -- first comment MUST be on 1 line.
    It is incorrect to say "return address" next to the label fact_loop

**see #522**

~~--Fig 5.14: too much space between the two parts~~

~~BUT: I think something needs to be added in that space -- an arrow
coming in from the left and turning down, to point to box 1 [p5].
Note that the box-and-pointer part has a pointer to the list itself
but the memory vector doesn't.  I see an arrow sketched in on my copy
and will check with Jerry.  What is your opinion (both of you)?~~

**Comment by TobiasWrigstad** [comment]
@martin-henz  The code in Fig 2.3 violates your Source style guide. OTOH, the way it is written highlights the relationship to the line-and-box diagrammes. I'll keep it as is unless you tell me otherwise.

**Comment by martin-henz** [comment]
> @martin-henz The code in Fig 2.3 violates your Source style guide. OTOH, the way it is written highlights the relationship to the line-and-box diagrammes. I'll keep it as is unless you tell me otherwise.

The code looks weird. It should follow our style guide. We should keep the indentation, which mirrors SICP.
