### ISSUE TITLE
PDF: <INDEX> not working for names

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#51]
We should allow a mechanism to include names in the index. One way could be:
```<INDEX>flatmap@<JAVASCRIPTINLINE>flatmap</JAVASCRIPTINLINE></INDEX>```
Similarly, subindices could include names:
``` <INDEX>half-interval method<SUBINDEX>half@<JAVASCRIPTINLINE>half_interval_method</JAVASCRIPTINLINE></SUBINDEX></INDEX>```
Neither of these currently work. I'm open to a different format or HTML tag for including names in the index and subindices.

**Comment by gerhean** [comment]
Works now by changing the braces to $.
May or may not create new problems in the future (may break if $ used in javascriptinline) but compiles fine at the moment.
