### ISSUE TITLE
PDF: Header subsection number off by one

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#52]
The subsection number in the header in this screenshot should be 1.2.2, and not 1.2.3:

<img width="470" alt="Screenshot 2019-06-10 at 12 00 45 PM" src="https://user-images.githubusercontent.com/30220768/59171850-a78e4a00-8b77-11e9-9500-7ed67a4bfe32.png">

**Comment by gerhean** [comment]
fixed
