### ISSUE TITLE
PDF: Figure 5.11 (p 476) code appears twice

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#522]
<img width="669" alt="Screenshot 2021-06-08 at 7 35 16 AM" src="https://user-images.githubusercontent.com/30220768/121100286-19afcd00-c82c-11eb-9dfd-e8023af3c11c.png">

**Comment by TobiasWrigstad** [comment]
@martin-henz What branch are you on? I am having trouble reproducing this error on my machine.

**Comment by TobiasWrigstad** [comment]
Never mind. I can reproduce now. Will fix.
