### ISSUE TITLE
Problem with definition of member in 2.3.1

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#525]
The definition of `member` given in [section 2.3.1](https://github.com/source-academy/sicp/blob/master/xml/chapter2/section3/subsection1.xml) has a problem.  If any of the items in the list are themselves lists then  the function returns an error `"Expected string on right hand side of operation, got array."`.  This presents a particular problem since the text has examples and exercises which attempt to use `member` with such an argument (e.g. [here](https://github.com/source-academy/sicp/blob/master/xml/chapter2/section3/subsection1.xml#L496)).  When you attempt to run such examples you will not get the answer that the book provides (e.g. try [this](https://source-academy.github.io/playground#chap=2&prgrm=PTAEGUEkGEAVQFLlAJgHQGY0EYBQuAzAVwDsBjAFwEsB7E0AWwFMGAjJgJwAoqKWAaUAA8AlKADeuUNNAcmFIh3pUAzgH0SRADZauoqTMMyA-KE06DRwwC5QvFqAC8z0AAsmAQwAmekZavSpkL+AbbMbJw8fAyCFB5UuqIiANy4AL744ezcAEQeAA75Wkw5-CHSWqoUXDlCpaCVKtV5hcX1OSoeRGQlIoI5AJ7tBUUl-fmeHDkiKUA) )

**Comment by mark-friedman** [comment]
Similar issues occur with the [definition of `equal` in that section](https://github.com/source-academy/sicp/blob/master/xml/chapter2/section3/subsection1.xml#L678).  The definition there tries to do the right thing but it's still not quite right.

For example, while the following works:
```
equal(list("foo"), "foo");
```
the following gets an error:
```
equal("foo", list("foo"));
```

**Comment by mark-friedman** [comment]
The book knows there is an issue: 

> “=== can only be applied to two numbers or two strings, and otherwise reports an error. 
> … 
> In chapter 3, we extend === such that it can be applied to any value and give meaningful results”

But doesn’t quite have the right workarounds.

**Comment by mark-friedman** [comment]
It looks like the problem with `equal` is different than the problem with `member`.  Note subtle difference between the builtin definition of `equal` (which works fine) below
```
function equal(xs, ys) {
  return is_pair(xs) 
         ? is_pair(ys) && 
          equal(head(xs), head(ys)) &&
          equal(tail(xs), tail(ys)) 
         : is_null(xs) 
         ? is_null(ys) 
         : is_number(xs) 
         ? is_number(ys) && xs === ys 
         : is_boolean(xs) 
         ? is_boolean(ys) && (xs && ys || !xs && !ys) 
         : is_string(xs) 
         ? is_string(ys) && xs === ys 
         : is_undefined(xs) 
         ? is_undefined(ys) 
         : is_function(ys) && xs === ys;
}
```

with the definition given in 2.3.1 as the solution to the exercise, and which demonstrates the issue:
```
function equal(xs, ys) {
    return is_pair(xs)
          ? (is_pair(ys) &&
              equal(head(xs), head(ys)) && 
              equal(tail(xs), tail(ys)))
          : is_null(xs)
          ? is_null(ys)
          : is_number(xs)
          ? (is_number(ys) && xs === ys)
          : is_boolean(xs)
          ? (is_boolean(ys) && ((xs && ys) || (!xs && !ys)))
          : is_string(xs)
          ? (is_string(xs) && xs === ys)
          : is_undefined(xs)
          ? is_undefined(ys)
          : // we know now that xs is a function
             (is_function(ys) && xs === ys);
}
```
So, I think the `equal` issue is just a typo!   I.e. the clause:
```
          : is_string(xs)
          ? (is_string(xs) && xs === ys)
```
should be
```
          : is_string(xs)
          ? (is_string(ys) && xs === ys)
```

**Comment by martin-henz** [comment]
Regarding equal: Yes this is a typo in the solution of exercise 2.54 has a bug. As you say: It should be ys instead of xs. The implementation of equal in the Source Accademy does not have this bug.

Regarding member: you are right: The examples should not use lists as elements of lists, because === is severely restricted in Source §2.

My intention for Source §2 was to create a strongly referentially transparent sublanguage of JavaScript. The substitution model should fully explain the language. That means that pointer equality should not be detectable:
```
function test(x, y) {
   return x === x;
}
test(pair(1,2), pair(1, 2));
```
should behave the same as:
```
const p = pair(1, 2);
test(p, p);
```
My solution was to restrict equality test === to disallow compound values as arguments. The cleanest way to achieve this in my view was to restrict === and !== to behave just like +, <, >, <= and >=: take only two strings or two numbers as arguments.

**Comment by martin-henz** [comment]
I'll fix the solution right away.

For the examples of member in the text, I need to through our editor. She already vetted 2.3.1 so we need her to vet the change.

**Comment by martin-henz** [comment]
fixed; more clarifications under way
