### ISSUE TITLE
PDF: prompt/input/output spacing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#529]
Revisit all pages with prompt/input/output spacing:
4.1.4, 4.2.2, 4.2.3, 4.3, 4.3.1, 4.4.1, 5.5.7

Fix the spacing in 4.2.2, currently too little space after the first "...input:":

<img width="527" alt="Screenshot 2021-06-14 at 9 56 19 AM" src="https://user-images.githubusercontent.com/30220768/121830159-fe930080-ccf6-11eb-9756-bcd60979caf3.png">

**Comment by TobiasWrigstad** [comment]
It seems that the space after "L-evaluate input:" is a `\PromptInputSpace` and the space after "L-evaluate value:" is a `\PreBoxCmd`.
The former is a negative (!) vskip of 0.15em and the latter is a vskip of 0.8em. 

So LaTeX is off the hook for this one. I'll look at the processing code to see why we generate different spaces here.

**Comment by TobiasWrigstad** [comment]
Sorry my mistake -- it is a `\InputOutputSpace` separating!

**Comment by TobiasWrigstad** [comment]
Darn -- I misread the message. It is a `\PromptInputSpace` in both cases of ""L-evaluate input:". I'm investigating.

**Comment by TobiasWrigstad** [comment]
OK, this one is interesting. It seems the interline spacing is affected by the height of the subsequent box. So if we change both snippets following the L-evaluate input: to the same number of lines, the spaces become the same. Not sure why this is. Reading very deep TeX stuff now.

**Comment by TobiasWrigstad** [comment]
Addressed in 5825c7a38502ac8533cfd5ff13ff9ccc71008ace
