### ISSUE TITLE
Contributing 

### ISSUE THREAD

**Issue by l-armstrong** [source-academy/sicp#534]
Hello, I've been going through the book and notice that some question don't have solutions. I was wondering how do you contribute a solution? It's not clear where to contribute. 

Thank you.

**Comment by samuelfangjw** [comment]
Hi @l-armstrong, there's some instructions [here](https://github.com/source-academy/sicp/wiki/Contributing-Exercise-Solutions)!

**Comment by l-armstrong** [comment]
Thanks !
