### ISSUE TITLE
! LaTeX Error: File `mathastext.sty' not found.

### ISSUE THREAD

**Issue by davidhaley** [source-academy/sicp#536]
Hello,

I downloaded the repo, ran `yarn install`, and received `./scripts/do.sh: line 61: latexmk: command not found`. I then `sudo apt-get install latexmk`, and reran `yarn install`, and it succeeded. Finally, I ran `yarn run pdf`, and it produces the following error log (`./latex_pdf/sicpjs.log`)

`This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian) (preloaded format=pdflatex 2021.6.16)  16 JUN 2021 17:40
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**sicpjs.tex
(./sicpjs.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-01-09> xparse <2020-03-03> (../mitpress/mit.cls

LaTeX Warning: You have requested document class `../mitpress/mit',
               but the document class provides `TimesAPriori_MIT'.

Document Class: TimesAPriori_MIT 2020/07/23 0.1
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifxetex.sty
Package: ifxetex 2019/10/25 v0.7 ifxetex legacy package. Use iftex instead.
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
)) (/usr/share/texlive/texmf-dist/tex/generic/iftex/ifluatex.sty
Package: ifluatex 2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
) (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
Package: fontenc 2020/08/10 v2.0s Standard LaTeX package
) (/usr/share/texlive/texmf-dist/tex/latex/psnfss/times.sty
Package: times 2020/03/25 PSNFSS-v9.3 (SPQR) 
)

! LaTeX Error: File `mathastext.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.72 ...ge[defaultmathsizes,italic]{mathastext}\fi
                                                  %^^M
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 368 strings out of 481252
 4084 string characters out of 5915888
 269461 words of memory out of 5000000
 17385 multiletter control sequences out of 15000+600000
 404193 words of font info for 28 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 68i,0n,74p,150b,40s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
`

**Comment by martin-henz** [comment]
Your LaTeX installation on your Debian Linux machine cannot find the style file mathastext.sty. One reason might be that the package texlive-latex-extra is not (properly) installed.

You may try to manually install this package with
```
apt-get install texlive-latex-extra
```
Another way would be to download the style file from CTAN and install the file in a place where LaTeX can find it.

**Comment by davidhaley** [comment]
Installing `apt-get install texlive-latex-extra` worked. Thank you!
