### ISSUE TITLE
WEB: Chrome is cutting off images

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#538]
Images don't show entirely at the moment. (Chrome on MacOS)

This example has pixels at the bottom missing:

<img width="652" alt="Screenshot 2021-06-18 at 12 17 17 PM" src="https://user-images.githubusercontent.com/30220768/122530860-8491ad00-d051-11eb-8744-72ad23889b55.png">

The actual image, displayed in the same browser:

<img width="652" alt="Screenshot 2021-06-18 at 12 17 40 PM" src="https://user-images.githubusercontent.com/30220768/122530889-8ce9e800-d051-11eb-89b9-72f6d90b7b99.png">

Note: This is not a problem on Firefox, also MacOS:

<img width="652" alt="Screenshot 2021-06-18 at 12 23 51 PM" src="https://user-images.githubusercontent.com/30220768/122530905-92dfc900-d051-11eb-8b97-f2501aa760da.png">

Investigation by @samuelfangjw shows that the problem goes away when the image has an integer pixel height:
"current height is 48.53px, if i change it to 48px or 49px the edges do not get cut off anymore"

Other examples have pixels on the left edge missing. Best check all edges of images on Chrome on MacOS. We may need to have a minimal padding in the SVG sources around all content and/or make sure that all image height and width are integer pixel values.

**Comment by TobiasWrigstad** [comment]
@martin-henz What do you mean by "pixel height"? Where is this coming from? Inside the SVG or from the generated code? 

(Also -- we need to rescale the SVGs somehow. Right now, some are huge and some are not.)

**Comment by TobiasWrigstad** [comment]
On the size of SVGs, I guess we need to bite the bullet of going through the book and give each SVG a proper pixel size (in the XML) that is compiled into the HTML.

**Comment by martin-henz** [comment]
Not sure if you understand the problem @TobiasWrigstad . The issue is an apparent Chrome bug which requires the px size of an SVG to be an integer.

The bug probably shows up in very few places. So my suggestion: We look out for this issue in "interactive" SICP JS, and fix the SVG size whenever necessary.

**Comment by martin-henz** [comment]
To illustrate my point, I have just pushed a change of this image
open static/img_javascript/ch2-Z-G-13.svg
I have changed its height (using inkscape) from 48.53px to 49px. This solves the problem:

<img width="976" alt="Screenshot 2021-06-24 at 4 24 10 PM" src="https://user-images.githubusercontent.com/30220768/123229181-a3d48280-d508-11eb-8099-6292a11aff9d.png">

Changing the height from 48.53px to 48px would have solved the problem too! (according to @samuelfangjw)

**Comment by TobiasWrigstad** [comment]
I understand the problem. I was just sloppy and started an unrelated discussion that popped into my head while I was thinking about this. 

What wasn't clear to me was the source of the pixel height, but now I see that this is metadata in the SVG set in inkscape. Thanks for clearing that up.

**Comment by martin-henz** [comment]
> What wasn't clear to me was the source of the pixel height, 
> but now I see that this is metadata in the SVG set in inkscape. 
> Thanks for clearing that up.

Yes, that metadata was not right in many places, which I have fixed when I saw them. There may still be a need for some fine-tuning. 

@samuelfangjw has an idea how to handle the scaling of SVGs across the board, to get a reasonable sizing in the "interactive" version.

I'm ok with closing this issue, and deal with similar issues when they come up.

**Comment by TobiasWrigstad** [comment]
Let's leave it open. I'll go through the SVGs and look for this and then close this. I can do that right after I'm done with #529 which is what I have been doing for the last 2 hours (and getting nowhere).

**Comment by martin-henz** [comment]
Sure. OK. An effective way to "go through the SVGs" would be to use "interactive" SICP JS:
https://sourceacademy.org/sicpjs

**Comment by TobiasWrigstad** [comment]
Yeah, great plan. That might be useful for other reasons too!

**Comment by martin-henz** [comment]
Hi Tobias:

Any news on #538?
https://github.com/source-academy/sicp/issues/538

I went through the images when doing the comparison edition and made a few
changes.

Can we close this issue?

-martin
http://www.comp.nus.edu.sg/~henz
