### ISSUE TITLE
WEB: Add index and search functionality to the interactive book

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#559]
It would be very nice to add search functionality to the interactive book.  The old search capability was a little wonky (I assume because of the dependence on Google) and it would be nice to have some more integrated search, but even the old mechanism would be better than nothing.

**Comment by martin-henz** [comment]
I agree and discussed with @samuelfangjw who is in charge of SICP JS in Source Academy.

We have a perfect setup for a great search: a JSON representation containing text snippets, and INDEX annotations in the XML sources. I'd guess a couple of weeks full time work to get a fantastic search feature. Volunteers should contact @samuelfangjw .

**Comment by martin-henz** [comment]
Regarding autocomplete, we could consider using this component: https://mui.com/components/autocomplete/

**Comment by martin-henz** [comment]
If every INDEX line translates to an object
```{ key: <number>,
  search: <string>,
  order: <string>,
  display: <string>,
  // following are optional
  open: <boolean>,
  close: <boolean>,
  footnote: <boolean>,
  subindex: { search: <string>,
                       order: <string>,
                       display: <string>,
                      // following are optional
                      open: <boolean>,
                      close: <boolean>,
                      footnote: <boolean> }
}```
we could do some preprocessing and deploy a data structure along with the frontend, which we can query when the user enters a search string. We can display the matching index entries in a 2-layer pull-down menu.

**Comment by martin-henz** [comment]
I suggest we do this in phases. The first phase would be to get a vanilla index up, where we ignore subindex entries, open, close, and footnote. We would also use the same string for search, order, and display. I think that would already be useful. Playing with that will allow us to see how to proceed.

**Comment by martin-henz** [comment]
Closing this: @yiwen101 came up with a vanilla version. Work in progress. See other issues with "Search: ..."
