### ISSUE TITLE
Broken inline LaTeX in the web book

### ISSUE THREAD

**Issue by TobiasWrigstad** [source-academy/sicp#560]
Something seems broken in the web edition. Screenshot from https://sourceacademy.org/sicpjs/4.1.2#p4

<img width="844" alt="bild" src="https://user-images.githubusercontent.com/364888/124826154-cf2d8780-df74-11eb-8196-9222ab4cb206.png">

As a side-note, maybe there should be a non-breaking space separating the << and the contents >>.

**Comment by TobiasWrigstad** [comment]
FWIW, I am using the latest firefox on macOS 10.15.7.

**Comment by mark-friedman** [comment]
I also noticed a few other bits of inline LaTex in section 4.1.2.

I am using Chrome on MacOS if that matters.
