### ISSUE TITLE
Multiple licenses in package.json file

### ISSUE THREAD

**Issue by samuelfangjw** [source-academy/sicp#564]
<img width="215" alt="Screenshot 2021-07-09 at 7 14 17 PM" src="https://user-images.githubusercontent.com/60355570/125069832-dc1fb780-e0e9-11eb-9bfe-1250bbeb3a3f.png">

Currently there are two separate licenses in the package.json file. Could I check if this is intended?

**Comment by martin-henz** [comment]
It's a bit complicated, see README.
