### ISSUE TITLE
XML processing: SPLITINLINE

### ISSUE THREAD

**Issue by TobiasWrigstad** [source-academy/sicp#568]
I was recently bitten by the fact that
```
<SPLITINLINE><SCHEMEINLINE>XXX</SCHEMEINLINE><JAVASCRIPT>YYY</JAVASCRIPT></SPLITINLINE>
```
renders as
```
{\JS~XXX~}YYY
```
We should definitely do something better here.

**Comment by martin-henz** [comment]
I think the specs are pretty clear about this:https://github.com/source-academy/sicp/wiki/SPLIT
The only elements inside SPLIT and SPLITINLINE should be SCHEME and JAVASCRIPT.
If you want to prevent other tags inside SPLITINLINE, the xml parser could give an error when it finds such a situation.

**Comment by martin-henz** [comment]
(specs are updated, but check not implemented)

**Comment by TobiasWrigstad** [comment]
Thanks! I'll do that after the book has gone to the press (if not before).
