### ISSUE TITLE
Section 4.3 text and examples use "retry" but REPL implementation uses "try_again"

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#569]
Also see the related issue (#570) that together with this one makes it hard to use section 4.3.

**Comment by martin-henz** [comment]
OK, will look into this. Or @anubh-v can you check? The SICP JS editor suggested "retry" to avoid the hyphen.

**Comment by martin-henz** [comment]
Fixed in js-slang, but js-slang version needs to be bumped; let's close this issue after that's done

**Comment by anubh-v** [comment]
My apologies for the late reply on this! Looking forward to the book!

**Comment by martin-henz** [comment]
No problem! You set it up really nicely. Only one constant needed to change.

**Comment by mark-friedman** [comment]
FYI, while this is fixed in the SICP embedded REPLs, it doesn't appear to be fixed in the standalone REPLs.  Maybe this is what @martin-henz meant by 
>Fixed in js-slang, but js-slang version needs to be bumped

**Comment by martin-henz** [comment]
This should be in the latest REPLs since a couple of days. Can you refresh your browser, empty  your cache etc @mark-friedman 
<img width="659" alt="Screenshot 2021-07-28 at 1 06 24 PM" src="https://user-images.githubusercontent.com/30220768/127266843-a6754198-d60c-4b65-ba0e-a9ed008a1fb1.png">

**Comment by mark-friedman** [comment]
Yeah, it must have been a cacheing issue.  Thanks.

**Comment by samuelfangjw** [comment]
Closing because this seems to be fixed.
