### ISSUE TITLE
Embedded playgrounds in section 4.3 don't start out using the Source 3 Non-Det variant

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#570]
This one makes it hard to use section 4.3, especially along with #569.

**Comment by samuelfangjw** [comment]
This issue is related to the old bug https://github.com/source-academy/frontend/issues/1704. Fixing that issue should fix this one as well.

**Comment by martin-henz** [comment]
OK, agree.

**Comment by samuelfangjw** [comment]
Tested, seems to be fixed by https://github.com/source-academy/frontend/pull/1863. 

<img width="1552" alt="Screenshot 2021-07-16 at 1 16 41 PM" src="https://user-images.githubusercontent.com/60355570/125895489-03996bb8-587b-47e5-91f3-b0b845d7d08e.png">
