### ISSUE TITLE
In Section 4.4, should we have process_assert?

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#572]
This is a bit speculative, but I wonder if it might make it easier to understand code and examples of section 4.4 if we made a further distinction between assertions and queries by having `process_assert` in addition to `process_query`.

This is somewhat related to #571.

**Comment by martin-henz** [comment]
This comes straight from SICP, and in SICP JS, we try not to change the original unless necessary. This is a debatable decision by the original authors, and I'd like to respect that decision.

**Comment by mark-friedman** [comment]
No problem.  I understand the desire to stay true to the original.
