### ISSUE TITLE
PDF: ordered lists <OL> in exercises

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#59]
Ordered lists `<OL>` in exercises should lead to a display as follows:
```
a. Here is the first part.
b. And here is the second part.
```
Currently, the list is numbered numerically:
```
1. Here is the first part.
2. And here is the second part.
```

**Comment by gerhean** [comment]
All OL are now labelled alphabetically

**Comment by gerhean** [comment]
OL outside exercise now use numbers

**Comment by martin-henz** [comment]
Great!
