### ISSUE TITLE
Code in section 5.3.2 gives an error when run

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#594]
If you try to run the example code in the embedded playground near the end of [section 5.3.2](https://sourceacademy.org/sicpjs/5.3.2) you get the following inscrutable error:
```
Expected 1 arguments, but got 0.
```
Given the amount of code (1145 lines) it is hard to pin down the cause of the error any further.

**Comment by samuelfangjw** [comment]
I'll try and find out what's going on here.

**Comment by samuelfangjw** [comment]
Not quite sure what's going on here, but i've narrowed down the issue.

Sometime during the running of the program, at line 830, (line 7 in the snippet below), `aprocs` is null.

```js
function make_operation_exp_ef(exp, machine, labels, operations) {
    const op = lookup_prim(op_exp_op(exp), operations);
    const aprocs = map(e => make_primitive_exp_ef(e, machine, labels),
                       operation_exp_operands(exp));

    function perform_operation_exp() {
        return op(map(p => p(), aprocs));
    }
    
    return perform_operation_exp;
}
```

At line 882 (line 2 in snippet below), `fn` is `make_broken_heart_ptr` and `args` is `null` (oddly by trial and error it seems to be expecting a non-null pair here instead).

function underlying_javascript_closure(fn) {
    return args => apply_in_underlying_javascript(fn, args);
}
