### ISSUE TITLE
SVG: fine-tuning figure 2.15

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#602]
<img width="607" alt="Screenshot 2021-08-08 at 1 40 42 PM" src="https://user-images.githubusercontent.com/30220768/128622098-94f521e5-092c-419b-bcd3-ca43bc522219.png">

> Figure 2.15 can use horizontal space a little better. No need
> to line break the (0, 0) remark. Iâ€™ll extend the figure left
> with white space to keep it centered.

It would be good to move the (0,0) label to the right, so it more
clearly refers to that point

**Comment by TobiasWrigstad** [comment]
Fixed now!
