### ISSUE TITLE
PDF: 5.5.1 enumerated list sticks out into left margin

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#603]
<img width="591" alt="Screenshot 2021-08-09 at 9 16 19 AM" src="https://user-images.githubusercontent.com/30220768/128651924-493e9c19-2b61-4b6e-ba60-93ac5df44e5b.png">

**Comment by TobiasWrigstad** [comment]
Wow, what might have happened here. Super strange. Well spotted!

**Comment by TobiasWrigstad** [comment]
Fixed!
