### ISSUE TITLE
Section 2.3.4  Figure 2.18 

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#605]
should have Times font for the node labels and no commas to separate the elements of the sets.

The text in the table should be changed accordingly: Remove all commas:

Initial leaves Merge Merge Merge Merge Merge Merge
Final merge
{(A,8), (B,3), (C,1), (D,1), (E,1), (F,1), (G,1), (H,1)} {(A,8), (B,3), ({C, D},2), (E,1), (F,1), (G,1), (H,1)} {(A,8), (B,3), ({C, D},2), ({E,F},2), (G,1), (H,1)} {(A,8), (B,3), ({C, D},2), ({E,F},2), ({G,H},2)} {(A,8), (B,3), ({C, D},2), ({E,F,G,H},4)}
{(A,8), ({B,C,D},5), ({E,F,G,H},4)} {(A,8), ({B,C,D,E,F,G,H},9)} {({A,B,C,D,E,F,G,H},17)}

**Comment by TobiasWrigstad** [comment]
@martin-henz the figure is changed to times now -- do you want the commas from the book removed too as part of this?

**Comment by TobiasWrigstad** [comment]
@martin-henz Best you check that I interpreted it correctly before we check this off.

**Comment by martin-henz** [comment]
Yes, good that you reopened this. I've removed the remaining extra commas from the table on the bottom of page 142, to match SICP. See email.

Fixed by: https://github.com/source-academy/sicp/commit/ff99346e73b42bfb86698ea7f26759acbf5963c4
