### ISSUE TITLE
PDF: vertical spacing of snippets

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#606]
Julie says:

Actually, the spacing above and below seems quite irregular.
I think it is more space above each displayed item than below.
But that seems wrong here, where I would expect uniform spacing.

I wonder what the global effect of a change is --
what kinds of things in the text are affected.

And why it got to be this way in the first place.
Because of some places in the text that want that irregularity?

Martin says:

Maybe this issue is specific to footnotes?

Example (mentioned by Julie): footnote 2 of chapter 3 (current page 192):

<img width="626" alt="Screenshot 2021-08-15 at 2 03 27 PM" src="https://user-images.githubusercontent.com/30220768/129468859-79ac60b3-0c95-4078-b77b-3d3ca898c751.png">

**Comment by TobiasWrigstad** [comment]
Subsumed by pagination
