### ISSUE TITLE
SVG: slight adjustment in text position

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#607]
<img width="709" alt="Screenshot 2021-08-15 at 5 17 17 PM" src="https://user-images.githubusercontent.com/30220768/129473596-e3b96de8-a9d1-4d8c-bb16-699b8cdb9646.png">

Those two text boxes need to move down by a point or two.

**Comment by TobiasWrigstad** [comment]
I've pushed a fix for this now. Please confirm and close!

**Comment by martin-henz** [comment]
It's fine!
