### ISSUE TITLE
WEB: Figure 2.2 too large

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#616]
<img width="1066" alt="Screenshot 2021-09-03 at 12 45 29 PM" src="https://user-images.githubusercontent.com/30220768/131951809-6decb416-3f19-4ab8-bf10-11596ba9c5f3.png">

**Comment by samuelfangjw** [comment]
I'll take a look at the pdf edition and adjust the image accordingly. Will submit a fix tonight!
