### ISSUE TITLE
PDF: Links from Solutions to Exercises go to wrong chapter

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#65]
Example:

<img width="499" alt="Screenshot 2019-06-17 at 12 00 19 PM" src="https://user-images.githubusercontent.com/30220768/59579363-2696fb80-90ff-11e9-94e1-80726afbff61.png">

The link goes to chapter 1 instead of chapter 2.

**Comment by gerhean** [comment]
fixed
