### ISSUE TITLE
WEB: 1.3.2 missing space

### ISSUE THREAD

**Issue by noamraby-ssky** [source-academy/sicp#745]
https://sourceacademy.org/sicpjs/1.3.2#p5
![image](https://user-images.githubusercontent.com/24941629/150825038-9d5c895b-db3f-42e4-aaec-ec8f82e7f569.png)

**Comment by martin-henz** [comment]
Thanks, @noamraby-ssky for the feedback. Fixed. Enjoy SICP JS!

**Comment by noamraby-ssky** [comment]
Thanks! 🙏
