### ISSUE TITLE
There's no vector primitive in JavaScript

### ISSUE THREAD

**Issue by NoamRa** [source-academy/sicp#756]
https://sourceacademy.org/sicpjs/2.1.3#p5 says `(an efficient implementation of pairs might use JavaScript's primitive vector data structure)`. There is no such primitive in JS. Looks like the paragraph wasn't updated from the Scheme version. 

Code is here:
https://github.com/source-academy/sicp/blob/dd5664ed0f0e606da399c438733cc108fda056ec/xml/chapter2/section1/subsection3.xml#L449

![image](https://user-images.githubusercontent.com/8105249/156001789-f19b3d47-1acc-491f-a11f-152049fe6e5c.png)

Thanks for making the book accessible! 🙏

**Comment by martin-henz** [comment]
Hi @NoamRa ! Thanks for bringing this up. This isn't a mistake. What is called "array" in JavaScript is usually called a vector, see C and C++. In Java, the notion of "vector" was gradually replaced by ArrayList. A footnote in 4.1.4 explains the terminology in more detail: https://sourceacademy.org/sicpjs/4.1.4#footnote-2

So basically: a pair pair(1,2) can be implemented easily in JavaScript as a two-component vector [1,2], which in the JavaScript community is called "array" [1,2]. This nicely coincides with the "box notation".
