### ISSUE TITLE
Docs: 2.3.2 Exercise 2.56 solution code have a small lint problem

### ISSUE THREAD

**Issue by clean99** [source-academy/sicp#779]
<img width="470" alt="Screen Shot 2022-05-18 at 8 14 39 PM" src="https://user-images.githubusercontent.com/53188310/169036309-d55a3ef0-4c28-4593-a22d-4c084c5c5fdf.png">
lack a space:

`head(x) ==="**" ` -> `head(x) === "**"`

**Comment by martin-henz** [comment]
Fixed by #780
