### ISSUE TITLE
Outdated epub instructions

### ISSUE THREAD

**Issue by danigayosog** [source-academy/sicp#781]
I tried to compile the epub version, and after see this issue https://github.com/source-academy/sicp/issues/434#issuecomment-765169378) I see that is no longer supported.

But in the wiki there is a specific section, https://github.com/source-academy/sicp/wiki/EPUB-Edition, that mentions it.

Could be a good idea to remove the instructions from wiki?

**Comment by elektronaut0815** [comment]
There was [PR #531], not sure what to make of it though.

**Comment by martin-henz** [comment]
I've removed the references to the epub version from the wiki, and from the folder javascript that contained the scripts for making the epub version. Thanks for pointing this out.

Of course feel free to start from scratch. It shouldn't be hard to make an epub version if you find the time and energy. I might offer this as a student project.

**Comment by Iey4iej3** [comment]
There are still remnants of epub: https://github.com/source-academy/sicp/blob/ba71acc224c9a794b3f09e98682f34c845a66a07/package.json#L43 and the description of `all` in Wiki page.
