### ISSUE TITLE
Docs: 3.2.4 Exercise 3.11 Code have a small problem

### ISSUE THREAD

**Issue by devinmugen** [source-academy/sicp#797]
![image](https://user-images.githubusercontent.com/42215787/187034033-cc882514-5f88-458f-80b2-2b896ae6e0aa.png)

`: "Unknown request: make_account";`

 -> 

`: error(m, "Unknown request: make_account");`

**Comment by martin-henz** [comment]
This is debatable. The original authors of SICP were striving for simplicity and often decided to use return values to indicate error to the hypothetical user. In this case the authors decided to not complicate the program, see https://xuanji.appspot.com/isicp/3-2-environment.html

Our maxime for adapting SICP to JS was to stick with the original, unless forced by the difference between Scheme and JS.

**Comment by devinmugen** [comment]
I looked at the Scheme version before raising Issues, and the Shceme version uses the error function.

![image](https://user-images.githubusercontent.com/42215787/187041535-b5713d62-18d3-4cb3-8e3e-5cfc04e2fa8e.png)

**Comment by martin-henz** [comment]
Sorry, I overlooked this. You are right. I've approved and merged the PR. Thanks for insisting.

**Comment by devinmugen** [comment]
Thank you for taking suggestions and for your contribution to SICP JS.
