### ISSUE TITLE
Solution to Exercise 3.29

### ISSUE THREAD

**Issue by taimoon** [source-academy/sicp#812]
Idea: ~(~a & ~b) = nand(~a, ~b) = ~~a | ~~b = a | b
```
function nand_gate(a1, a2, out){
    const tmp = make_wire();
    and_gate(a1, a2, tmp);
    inverter(tmp, out);
}
function or_gate(a1, a2, out){
    const not_a1 = make_wire();
    const not_a2 = make_wire();
    inverter(a1, not_a1);
    inverter(a2, not_a2);
    nand_gate(not_a1, not_a2, out);
}
```
The delay time of the or-gate is 
nand_gate_delay = and_gate_delay + inverter_delay
or_gate_delay = nand_gate_delay  + inverter_delay = and_gate_delay  + 2 * inverter_delay

**Comment by martin-henz** [comment]
fixed in commit https://github.com/source-academy/sicp/commit/f8533008ed190ddb268c8e8f984159517ac2d719
