### ISSUE TITLE
All: Proposal on image sizing and styling

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/sicp#83]
### Issue
Figures [3.29](https://sicp.comp.nus.edu.sg/chapters/64#fig_3.29) and [3.30](https://sicp.comp.nus.edu.sg/chapters/64#fig_3.30) in [Chapter 3.4.1 The Nature of Time in Concurrent Systems](https://sicp.comp.nus.edu.sg/chapters/64) are really huge. Once Chapter 3.4.1 is loaded to the screen, these figures require excessive horizontal scrolling. Even when fully zoomed out and on full screen, figure 3.29 still does not fit on screen and figure 3.30 barely fits.

### Screenshots
These screenshots show fully zoomed-out browsers.
Firefox: 
![](https://imgur.com/F06FzS6.png)

Chrome:
![](https://imgur.com/XpViBZI.png)

### Browser versions
Mozilla Firefox 67.0.4
Google Chrome 75.0.3770

**Comment by martin-henz** [comment]
I think we should re-visit images sizes. Previously, I've argued to not change the image size, and instead just use the "natural" size of the images. This is probably not a good idea when we want to support reflowable ebook formats.

So I would like to renege on this: Let me propose the following across-the-editions policies on images:

(1) All images should look good when their width occupies much of the available page width.
(2) All images should have black graphics and text on a white (non-transparent) background.
(3) All images should use the PNG format.

What do you all think?

**Comment by gerhean** [comment]
Images in the PDF are already limited to a maximum size (smaller than a page)

**Comment by martin-henz** [comment]
OK, how about this: 
(1) We make sure, we never stretch pictures. We only shrink them.
(2) We only shrink pictures when they would be wider than the page. In that case, we shrink them to (almost) the width of the page.

**Comment by martin-henz** [comment]
Done by: https://github.com/source-academy/sicp/pull/113
