### ISSUE TITLE
Problem in 3.5.1

### ISSUE THREAD

**Issue by clean99** [source-academy/sicp#839]
<img width="825" alt="Screenshot 2022-11-14 at 2 44 18 PM" src="https://user-images.githubusercontent.com/53188310/201592815-fddc7318-f6fd-442f-bf9f-9dc3ef717a28.png">

I think here the `stream_filter` will return 
```js
pair(head(stream), 
     () => stream_filter(pred, stream_tail(stream)));
```
instead of
```js
pair(head(stream), 
     stream_filter(pred, stream_tail(stream)));
```

If it calls `stream_filter` directly in the tail, it will become an ordinary list?

**Comment by martin-henz** [comment]
Yes, you are right! Thanks for this keen observation! Will fix this in the next printing, and in the online edition.
