### ISSUE TITLE
EPUB: SUBHEADING should not be numbered

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#91]
<img width="580" alt="Screenshot 2019-07-02 at 8 23 08 AM" src="https://user-images.githubusercontent.com/30220768/60474138-dabd8800-9ca2-11e9-93a8-05b12b7f8c00.png">

In LaTeX, this is done using *, for example:
\section*{Applicative order versus normal order}
or
\subsection*
or 
\subsubsection*

**Comment by jolynnn8D** [comment]
<img width="484" alt="Screenshot 2019-07-08 at 10 19 53 PM" src="https://user-images.githubusercontent.com/41572120/60817585-89dfef00-a1ce-11e9-8d80-cd121b37cd19.png">

Fixed
