### ISSUE TITLE
EPUB: Subsection label for Chapter 1.1.3 displayed incorrectly

### ISSUE THREAD

**Issue by jolynnn8D** [source-academy/sicp#96]
LABEL tag needs to be moved outside of the NAME tag 
<img width="672" alt="Screenshot 2019-07-03 at 12 08 13 AM" src="https://user-images.githubusercontent.com/41572120/60528368-e783bf80-9d26-11e9-8ef1-68ce134ddc51.png">

**Comment by martin-henz** [comment]
Done, see https://github.com/source-academy/sicp/pull/97
