### ISSUE TITLE
Can't build the "web" version. Command "web" not found.

### ISSUE THREAD

**Issue by cgbarros** [source-academy/sicp#965]
Hello! I'm trying to run `yarn web` to build the website and proofread an exercise solution but I'm getting `Command "web" not found.`. When I try to run `yarn all` and `yarn prepare` I see that the `html_js` directory is empty.

I also tried to run `yarn process web` but I got `TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined` at `createMain (/home/cdebarros/sicp-source-academy/javascript/index.js:246:8)`

The split version doesn't seem to show modifications to the XML files and the pdf version doesn't show exercise solutions.

Is there a way for me to preview the exercise solution so I can proofread it?

**Comment by martin-henz** [comment]
The wiki documents the use of the commands 
```
yarn json
```
and 
```
yarn tryjson
```
I don't see any references to a `web` command.
